spring.application.name=fixmycity-backend

spring.datasource.url=jdbc:oracle:thin:@fixmycity_high?TNS_ADMIN=src/main/resources/Wallet_FIXMYCITY
spring.datasource.username=ADMIN
spring.datasource.password=IDVISystems5
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.connection-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

jwt.secret=FixMyCitySecretKey2024Oracle#Spring!
jwt.expiration=86400000